[package]
name = "argen"
version = "1.1.0"
authors = ["Matt Lee <matt@kynelee.com>", "Lucas Morales <lucas@lucasem.com>"]
edition = "2018"

[dependencies]
getopts = "0.2"
regex = "1.3"
serde = { version = "1.0", features = ["derive"] }
toml = "0.5"
