[[positional]]
c_var ="out_file"
c_type = "char*"
help_item = "IN_FILE"
help = "an input file for this example program"

[[positional]]
c_var = "in_file"
c_type = "char*"
help_item = "OUT_FILE"
help = "where we'll put some output"
optional = true

[[positional]]
c_var = "words"
c_type = "char*"
help_item = "WORD"
help = "word(s) of interest"
optional = true
multi = true

[[non_positional]]
c_var = "block_size"
c_type = "int"
help_item = "num"
help = "set the block size, defaults to 12."
long = "block-size"
short = "b"
aliases = ["bs"]
default = "12"

[[non_positional]]
c_var = "fave_number"
c_type = "int"
help_item = "num"
help = "your favorite number"
long = "fav-number"
default = "0xDEADBEEF"

[[non_positional]]
c_var = "quiet"
c_type = "int"
help = "disable output"
long = "quiet"
short = "q"
no_arg = true

[[non_positional]]
c_var = "username"
c_type = "char*"
help = "your name"
long = "name"
default = "John Smith"
