[[positional]]
c_var ="out_file"
c_type = "char*"
help_name = "IN_FILE"
help_descr = "an input file for this example program"
required = true

[[positional]]
c_var = "in_file"
c_type = "char*"
help_name = "OUT_FILE"
help_descr = "where we'll put some output"

[[positional]]
c_var = "words"
c_type = "char*"
help_name = "WORD"
help_descr = "word(s) of interest"
multi = true

[[non_positional]]
c_var = "block_size"
c_type = "int"
help_name = "num"
help_descr = "set the block size, defaults to 12."
long = "block-size"
aliases = ["blocksize", "bs"]
short = "b"
default = "12"

[[non_positional]]
c_var = "fave_number"
c_type = "int"
help_name = "num"
help_descr = "your favorite number"
long = "fav-number"
default = "0xDEADBEEF"

[[non_positional]]
c_var = "quiet"
c_type = "int"
help_descr = "disable output"
long = "quiet"
short = "q"
flag = true

[[non_positional]]
c_var = "username"
c_type = "char*"
help_descr = "your name"
long = "name"
default = "John Smith"
